### ISSUE TITLE
Prices not syncing

### ISSUE THREAD

**Issue by jordanhan1992** [wootwoot1234/Superhost-Tools#10]
Hello,

Is anyone else having trouble syncing prices to Airbnb? I have smartpricing enabled on Airbnb but can't seem to get my calendar to reflect Superhost Tools pricing. 

Thanks!

**Comment by jordanhan1992** [comment]
Here is my listing if that helps, maybe I don't have the right settings on the airbnb side?

[https://www.airbnb.ca/rooms/7581561?s=51](url)

**Comment by wootwoot1234** [comment]
Hmmm...  The prices sync every 24 hours, could that be it? You can also manually initiate a sync by clicking the sync button.  If that isn't it, what is the first part of the email address (everything before the @ symbol) you used to sign up and I'll take a look.  Do you have more than one listing? If so which listing is it?

**Comment by jordanhan1992** [comment]
Hey Tom, I did initiate a manual sync and I think I figured it out.

The sync seems to work when I have only one pricing rule (i.e. Airbnb Smart pricing +15%) but when I add additional rules, syncing seems to stop. The email I used to sign up is 'jordanhan1992'

Thanks so much!

**Comment by wootwoot1234** [comment]
Could it be that you have a minimum price set on either Airbnb.com or is superhost tools? There was another user that had a minimum price Airbnb.com and when superhost tools tried to set a price lower than the minimum it was ignored.

**Comment by jordanhan1992** [comment]
mhmm good point. I did have both set at 68. I just went into Airbnb and lowered minimum price set to 35 so it shouldn't interfere with superhost tools. Giving it a few minutes to see if it works

**Comment by wootwoot1234** [comment]
BTW, Superhost tools is set to only allow manual updates every hour.

**Comment by wootwoot1234** [comment]
If you want I can log into the database and change the time it synced last so you can test it.  Let me know.

**Comment by jordanhan1992** [comment]
That would be awesome if you could do that!

**Comment by wootwoot1234** [comment]
Ok, set it back.  You should be able to manually sync again.

**Comment by jordanhan1992** [comment]
Everything works perfectly now, thanks so much!

**Comment by wootwoot1234** [comment]
Great, glad that was it.  I need to display a warning to users when this happens so it's not so confusing.  You're not the only person that's had this issue.  Thanks for bringing it to my attention.
