### ISSUE TITLE
SMS Message Rule

### ISSUE THREAD

**Issue by christianhartman** [wootwoot1234/Superhost-Tools#12]
Provide option to send message rule to SMS and email.

**Comment by wootwoot1234** [comment]
Hey Christian,

I've looked into adding sms to superhost tools but it's prohibitively expensive to send text messages.  There is a way to send text messages to some carriers using email.  If you know what cell service your cleaner uses you can try adding emailing them a text message.  If that works, you could try using that email in superhost tools.  Here's a list of providers and their emails:

https://github.com/typpo/textbelt/blob/master/lib/carriers.js

Let me know if that helps/works.

**Comment by christianhartman** [comment]
Using carrier email to SMS text email address worked for AT&T today.    It arrived around the scheduled time in the rule....off by a few minutes.

**Comment by wootwoot1234** [comment]
Ok, great!  Maybe I'll add the option to send an sms with a big disclaimer that states that it doesn't work with all carriers and should be verified.  I'm currently move the code to a new server (the site outgrew the other server) and making it more efficient.  Once that's done.  I'll make the sms my first priority.

**Comment by wootwoot1234** [comment]
I added the ability to send text messages.  Give it a try and let me know if it works like you'd expect.

**Comment by Kashk** [comment]
Hi there!

Thanks for adding it. I found this repo earlier today but I wasn’t able to get the code to work. I loaded it on Heroku but after connecting my account it said go to pricing or messaging but I didn’t see those options. I tried to re-conenct a few times but noting ever happened. 

Keep up the good work!

K

**Comment by wootwoot1234** [comment]
@Kashk have you taken a look at your logs?  Since this is not related to sms please start a new issue.  Thanks!

**Comment by christianhartman** [comment]
Tested this morning.  Works for me.  Thank you!

**Comment by wootwoot1234** [comment]
Great!  Thanks for getting back to me.
