### ISSUE TITLE
Monthly summary email

### ISSUE THREAD

**Issue by christianhartman** [wootwoot1234/Superhost-Tools#13]
Feature sends one month calendar with check-in and check-out dates to email address.  Helpful for my cleaners to see the month ahead.

**Comment by wootwoot1234** [comment]
I don't see this being useful for my listings.  We typically get most of our bookings within a month of the check-in date so that email wouldn't be that helpful.  I use the email feature to send my cleaners an email when someone books and a reminder the morning of the cleaning.   Are you typically completely booked a month in advance?

**Comment by christianhartman** [comment]
My airbnb listing is located in a vacation area of the United States.  I will have my June/July/Aug completely booked by March.  I typically download the listings to excel and send over the file to my cleaners at the end of each month so they can plan their staff around my needs.  I have yet to receive a booking in the same month...ie it is always several months out.

**Comment by wootwoot1234** [comment]
I see.  Why not share a link to your calendar with your cleaners?

**Comment by christianhartman** [comment]
I shared a Google Drive link to the spreadsheet but she was an Apple user and became confused.  I know...it's annoying.  The resolution was to email a spreadsheet of the upcoming listing at the beginning of each month.  I am sure I could use Zapier/IFTTT to do something similar but thought this might be a feature that others might see as valuable.

**Comment by wootwoot1234** [comment]
What about sharing your accounts ics file with them. Here’s how you [import it on iOS.](https://www.google.com.mx/amp/s/www.imore.com/how-subscribe-calendars-your-iphone-or-ipad%3Famp)

I’ll leave this issue open. If others would like this feature please comment.

**Comment by wootwoot1234** [comment]
I'm going to close this.  Unfortunately this is not a feature I I have time to add right for now.
