### ISSUE TITLE
Linking Airbnb account is not working

### ISSUE THREAD

**Issue by asafrot** [wootwoot1234/Superhost-Tools#2]
Hi,

I tried to link my Airbnb account. the website it will take few minutes to initialize but an hour passed and nothing........ crickets?

Thanks

Asaf

**Comment by wootwoot1234** [comment]
Hey Asaf,

You found a good bug here!  👍 

For some reason, it looks like Airbnb needs to verify that you intended to use a tool like Superhost Tools.  You need to login to your account on [Airbnb.com](https://www.airbnb.com) and complete any verification it prompts you for.  Once you've verified your account, head back to [Superhost Tools](http://superhosttools.com) and add your Airbnb account again.

I've added more better error handling to Superhost Tools so it handles this use case better in the future.  

Let me know if you have any more problems and if this issue is solved so that I can close it.  Thanks!

**Comment by asafrot** [comment]
Hi Tom,

I logged into my airbnb account and it's verified in all possible ways.
I also saw you guys logged into the account:

[image: Inline image 2]

this is the message I get when I try to add my account on your system

[image: Inline image 1]

**Comment by wootwoot1234** [comment]
Those images didn't come through.  Can you repost them?

**Comment by asafrot** [comment]
hope this will go through

**Comment by wootwoot1234** [comment]
No, maybe try uploading them to something like [https://imgbb.com/](https://imgbb.com/) and post the link?

**Comment by asafrot** [comment]
try this link

https://drive.google.com/open?id=0B7sovVMYvHFvcWJ4NXdDNlNMZUU

**Comment by wootwoot1234** [comment]
Just want to double check. You logged into Airbnb and went through the verification process, then logged into Superhost tools, clicked the update button and renters your Airbnb credentials?  It's important that you update the credentials on Superhost tools after the verification on Airbnb.

**Comment by asafrot** [comment]
I've completed the verification process a long time ago and always using
the correct credentials.

**Comment by wootwoot1234** [comment]
You need to update your credentials on Superhost tools after the Airbnb verification process. Basically, you're telling Superhost tools to try again. If you already did that, it must not be fixed and I'll have to look into it more in the morning.  Sorry for the inconvenience.

**Comment by asafrot** [comment]
all good.
we like your business and service and have a good feeling about this
service.
yes I did everything you mentioned and it still not working.

let me know when you fix the bug and I'll try again

good night

Asaf

**Comment by wootwoot1234** [comment]
Hey Asaf,

I did some more digging and this is what I came up with.  Airbnb uses a service called Airlock that helps keep accounts secure by locking people out when they sign in from places that are not expected.  Long story short, you need to visit airbnb and verify that it's you that is logging in to Superhost Tools.  I've added more detailed error handling when adding an account.  If you try to add your account you should now see a error that looks like this:

![airlock screen on superhost tools](https://user-images.githubusercontent.com/419609/29044303-703c6b7c-7b84-11e7-832f-d0c9ccd3e8e4.jpeg)

There is now a link in the error that will (hopefully) take you to the page on Airbnb.com where you will need to verify that it's actually you.  That page should look like this:

![airbnb keep account secure](https://user-images.githubusercontent.com/419609/29044347-a779380e-7b84-11e7-8b97-5c3602ca5c2b.jpeg)

Once you've completed the verification, return to Superhost Tools and try to add your account again.  It should work (fingers crossed).

Please let me know how it goes and thanks for working with me to get this issue solved.

Best,
Tom

**Comment by asafrot** [comment]
Hi Tom,

thanks for your detailed instructions.
I followed your instructions, the link to the verification in Airbnb worked
fine, I verified it and tried to add my airbnb account again in SuperHost
Tools. however, I got the same error as I got before. see photo in this
link:  https://drive.google.com/open?id=0B7sovVMYvHFvZEc5SUI2M1hmbWc

Asaf

**Comment by asafrot** [comment]
also I checked to log-in history
it looks you're still logged in
see this pic

https://drive.google.com/open?id=0B7sovVMYvHFvNE9KblRRSHJDblU

**Comment by wootwoot1234** [comment]
Wow!  One bug after another.  :)  I'm not sure why this is happening with your account and not others.  

Looking at the logs, you were able to login fine but it had an issue downloading your listing information.  The good news it, I think I found and submitted a fix, can you try again?

Thanks,
Tom

**Comment by asafrot** [comment]
you did it!

well done and thanks

I guess you'll hear from me again in the next Bug

cheers,

Asaf

**Comment by wootwoot1234** [comment]
That's a relief!  I'm glad it's working now.  Yes, please let me know if you find another bug.  If you could also let me know of anything that's confusing that you think could be made clearer plase let me know.  I want to make this thing easy to use and any input is helpful.

Tom

**Comment by asafrot** [comment]
Thanks bro,

really appreciate your effort.
for now including automated sms messages to guests and cleaners will be
very helpful.

cheers

Asaf

**Comment by wootwoot1234** [comment]
That's a good idea.  I just added (a few days ago) the ability to email cleaners but not sms.  I haven't looked into it in a few years but last time I checked, all the sms services were pretty expensive and since this is a free service I can't justify paying for it.  I might look into it though.

**Comment by asafrot** [comment]
Thanks Tom,

my friend and I are looking for a way to use your trigger with a 3rd party
sms provider.
another small bug, in the attached review message I disabled the message
for the guest but in when I review the upcoming messages on the dashboard
the message to the guest still exist together with the review

https://drive.google.com/open?id=0B7sovVMYvHFvdXdUUmxoMTJkOGM


Asaf

**Comment by wootwoot1234** [comment]
I want to make sure I understand you.  If you create a message rule to review the guest without a message to the guest, the message still shows like it will send on the dashboard when it should just show a review? I think it's a cosmetic bug but I'm not sure. It's probably best if you delete that rule for now and I'll see if I can fix it tomorrow. Thanks for the heads up, I'll let you know when it's fixed.

**Comment by wootwoot1234** [comment]
Oh, if you figure out how to send SMS using email let me know.

**Comment by wootwoot1234** [comment]
I fixed the bug.  It was cosmetic only but either way, it's fixed.  Let me know if you find more.

**Comment by asafrot** [comment]
you did it again :)

thanks

**Comment by asafrot** [comment]
I'm currently using messagebird to apply the email to sms. with superhost,
I will send an email to my Gmail with the desired sms as message body. in
my Gmail I created a filter that forwards the same message as an SMS. a
useful feature will be [TEST] button on superhost dashboard that sends the
message instantly.

Asaf
