### ISSUE TITLE
Unable to add more than one airbnb account?

### ISSUE THREAD

**Issue by ferniebnb** [wootwoot1234/Superhost-Tools#20]
It won't let me add additional airbnb accounts

**Comment by wootwoot1234** [comment]
@ferniebnb, are you seeing any errors?  What happens when you try to add another Airbnb account?  I just tested adding an Airbnb account to my account and it worked fine.  Could it be a bad Airbnb username/password?

**Comment by Kashk** [comment]
Hi there, I am having the same problem. I’ve never been able to successfully connect my account to Supertools both on my own system and on your site. I logged in using the same email and password on Airbnb to confirm it was correct. I’d love to play with the tool but have yet to see it in action.

Best,

K

**Comment by wootwoot1234** [comment]
@Kashk can you give it another try on superhost tools right now?  Let me know what happens when you add the account.  I'll also keep an eye on logs and see if I can figure out the problem.

**Comment by Kashk** [comment]
Know what they say when you go to the mechanic with a broken car and he turns it on without a problem…seems to be the case :)

It’s initializing right now and now I just got it to load for the first time!

Good work!

**Comment by wootwoot1234** [comment]
@Kashk Ha, great! Happy to help.  ;)

**Comment by ferniebnb** [comment]
It works now.  It was not previously giving me the “airlock” warning and link option.  Now it does and i’ve successfully  added a few more accounts.
Thanks

**Comment by wootwoot1234** [comment]
@ferniebnb good.  I made a small fix to the error handling so hopefully that was what solved it.
