### ISSUE TITLE
Price not syncing?

### ISSUE THREAD

**Issue by h2ofan** [wootwoot1234/Superhost-Tools#24]
I have setup my own heroku website & repo. 

It seems that the price & calendar are not syncing and that I have to do that manually each time, is it expected?

**Comment by wootwoot1234** [comment]
Are you pinging the following links every 15 min or so?

http://yourHerokuDomain.com/checkRules
http://yourHerokuDomain.com/updatePricing

**Comment by wootwoot1234** [comment]
I'm going to close this due to no response.
