### ISSUE TITLE
 Heroku App Deploy link Airbnb account password incorrect.

### ISSUE THREAD

**Issue by UltraFlux** [wootwoot1234/Superhost-Tools#26]
I did a deploy to Heroku and can't get past login. Tested password on Airbnb so I know its not password related.

2017-12-10T20:59:32.295814+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/addAccount" host=.herokuapp.com request_id=a23c03a8-73cf-4b01-8691-4e55007f3472 fwd="" dyno= connect= service= status=503 bytes= protocol=https

Mozilla | Ashburn, VA, United States | 10 minutes ago (Not me and seems tied to Heroku

I see activity in my Airbnb log which is likely the login. Perhaps need more information in the log to debug further.

**Comment by UltraFlux** [comment]
Additional Data:
After doing the above I believe it linked to some extent. When I logged out and logged into admin it say my link was successful. However, none of the menu options are available.

https://gyazo.com/5a89dba422c76fe033a6685ed0c5a377

**Comment by wootwoot1234** [comment]
Hey @UltraFlux.  Sorry for the late response.  Did you ever figure this out?
