### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by damiike** [wootwoot1234/Superhost-Tools#3]
Hi Tom,

I just installed ST on my own unix VPS.

I've installed all the pre-requisite software.

When I start the site, it asks to login or register.

When I try to register, no matter what the email address is, I get the following error message:

That email already exists. Try logging in instead. 

Please help. 

Thank you!!!

Mike

**Comment by wootwoot1234** [comment]
Hey Mike,

That's a funny one.  Can you post the node logs?  

This is a shot in the dark but are you sure you have your database setup correctly?  

Let me know.

Tom

**Comment by damiike** [comment]
Hi Tom,

I had my server support guys install it all, so I assume it is done correctly.

Is there a way to check that I can do?

I ran the command: node app.js > app_log.log 2> app_err.log

Error Log:

(node:32415) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
(node:32415) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
crypto.js:635
    throw new TypeError(
    ^

TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:635:11)
    at Object.exports.pbkdf2 (crypto.js:623:10)
    at RandomBytes.ondone (/home/st.domain.com/node_modules/passport-local-mongoose/lib/passport-local-mongoose.js:61:20)

Log:
Express server listening on port 1337
NOT RUNNING IN PRODUCTION MODE, APP WILL NOT SEND MESSAGES OR SET PRICES
/register

Let me know if this helps.

Thanks for the help!

Mike

**Comment by wootwoot1234** [comment]
I'm not sure if I'm going to be very helpful.  It seems like maybe the version of crypto you have installed is different than the one we I'm using.  The funny thing is I don't include crypto but I think passport-local-mongoose must.  I wish I could be more helpful.  If you're server guy can't help you maybe try posting a question on Stackoverflow?

Another thing you'll need to do is change your `process.env.NODE_ENV` and set it to "production".  If you don't do that the code will think you're running it on a test server and will not send messages or adjust your prices.

Can I ask, why are you trying to spin up your own version?  Why not just use SuperhostTools.com?  Just curious.

**Comment by wootwoot1234** [comment]
I just had an idea.  What version of node is your server running?

`node -v`

you should be running 7.9.0.  If you're not, try installing or ask your server admin to install the correct version.  I'm not sure but that error might be because you have a newer version of node.

Tom

**Comment by damiike** [comment]
Hi Tom,
Thanks for the reply.
I'd prefer to run the app in my own environment where I have my own support guys for any server related issues. They have SLA's.
I wanted to test the app out for now as I manage multiple properties and would be interested in helping improve the project. I've also discussed this with a friend of mine that is interested as well that does the same.

I've had my server guys change Node down from v8 to v7 as per your recommendation. Let you know if that fixes it.

Cheers,
Mike

**Comment by damiike** [comment]
Hi Tom,

My server guys could only change it to v7.10.1

They reinstalled the app.

I can now register and login, but it the app shows the menu and a white screen with nothing in it.

Any idea what this could be?

See screenshot here: http://imgur.com/a/7C78O

Thanks,
Mike

**Comment by wootwoot1234** [comment]
Hey Mike,

Can you send me the logs again?

Thanks,
Tom

**Comment by damiike** [comment]
Hi Tom,

Error Log:

(node:8809) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::1337
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at Function.app.listen (/home/sps/st.strikepropertyservices.com/node_modules/express/lib/application.js:535:24)
    at Object.<anonymous> (/home/sps/st.strikepropertyservices.com/app.js:59:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

Thanks,
Mike

**Comment by wootwoot1234** [comment]
`EADDRINUSE` means that the port number is already in use.  In this case it's port number 1337.

**Comment by damiike** [comment]
isn't that port used by the app? that's what is showing up on the readme doc when I look at installing local.

Just not sure what to say to my server guys to fix that.

**Comment by wootwoot1234** [comment]
Yes, that's the default port but something else on the server is using that
port.  You need to set `process.env.PORT` to a port that is available.

**Comment by damiike** [comment]
Hi Tom,

My server guys looked into it, they responded that:

Port 1337 is used only by the application(node) itself which is defined in app.js as below:
====
app.set('port', process.env.PORT || 1337);
=== 

Anything else I could check?

Mike

**Comment by wootwoot1234** [comment]
Yes, that's the default port but something else on the server is using that
port.  You need to set `process.env.PORT` to a port that is available.

**Comment by wootwoot1234** [comment]
Did you get it working?

**Comment by damiike** [comment]
Hin Tom,

I had the server guys change it to port 1340 and ran the logging again.

Same issue.

Error Log:

(node:20796) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::1340
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at Function.app.listen (/home/sps/st.strikepropertyservices.com/node_modules/express/lib/application.js:535:24)
    at Object.<anonymous> (/home/sps/st.strikepropertyservices.com/app.js:59:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

Is there anything else I should test?

Thanks for the help!!!

Mike

**Comment by wootwoot1234** [comment]
I'm not sure. Have you thought about running it on Heroku?

**Comment by damiike** [comment]
I've decided to run it on Heroku. :)
