### ISSUE TITLE
Prices far away seem off (240+days)

### ISSUE THREAD

**Issue by popepay** [wootwoot1234/Superhost-Tools#31]
Hello,

I am seeing an issue, not sure if it is an AirBnB bug or something else.
For my listing, all prices past september 10 2018 (until january 2019: 240 days away and more) are all exactly identical (and higher than anything I have ever set).

This is the "airbnb smart price" displayed in Superhost-Tools.

Could there be a glitch? Do you see the same issue?

**Comment by wootwoot1234** [comment]
I’ve seen this before on my listings. Take a look at your smart price
recommends on Airbnb but I think it’s just Airbnb’s smart pricing being
crazy.

On my listings I set both a min and a max price and only let Airbnb’s smart
prices fluctuate within a range.

**Comment by wootwoot1234** [comment]
I'm going to close this due to inactivity.
