### ISSUE TITLE
New Message - anyone who just does an inquiry

### ISSUE THREAD

**Issue by LoriGreiner** [wootwoot1234/Superhost-Tools#32]
Hi Tom,
Have you developed a way to send a message to anyone that just does an inquiry? Something that says , Thanks for your interest, I will get back to you with more information ASAP

**Comment by wootwoot1234** [comment]
Just got another request for this feature:

> I have seen on other software that you can enable an autoreply to general inquiries, usually it only sends this message if you have not already replied and you can also set the delay to send in minutes. Neat feature, would love to see it here.

**Comment by bkkEvan** [comment]
Yes it is a useful one

**Comment by wootwoot1234** [comment]
I've added inquiry messages now.  You can now create rules based on inquiries.
