### ISSUE TITLE
Airlock Verification

### ISSUE THREAD

**Issue by gabibora** [wootwoot1234/Superhost-Tools#34]
Hi Tom,

First thanks for this great tool. I used your code on a clean install on my server. I have problems with airlock 
verification for some accounts. I saw that you have on the live account a verification system similar with verification system from aibnb but here I don't see any endpoints, or modals to help me verify the accounts via email or phone. 
Could you please help me with that part ?

**Comment by wootwoot1234** [comment]
The temporary solution for the captcha is to wait 24 hours and try again.  Most users have reported success.

**Comment by gabibora** [comment]
Hey Tom I will try investigate the captcha problem, only once I had that problem, captcha  is not a big issue yet for me at this point, I would try to use this  (email, phone text) verification system you have. I need a start there I will see if is the correct path or not :)

**Comment by Kashk** [comment]
Hi everyone,

I'm also trying to work on the captcha. Is there an update to the code I can try to re-deploy to make sure I have the latest version. It looks like the last update was 7 months ago which I know isn't true :)

**Comment by wootwoot1234** [comment]
@Kashk glad to see you're using the code and trying to fix this issue.  I could really use some help with the login problem.  I'm sorry there haven't been any updates in a while.  You're right, I have been working on updates to the code but it's not ready to be committed to github.  Sorry.

**Comment by AvkashKana** [comment]
Tom,

Thanks for reaching out. If you’re free to chat PM me and let’s synch up over a call. 

My email is avkash.patel1@gmail.com <mailto:avkash.patel1@gmail.com>

Best,

Avkash

**Comment by wootwoot1234** [comment]
@AvkashKana sent you an email.

**Comment by gabibora** [comment]
@wootwoot1234  Tom, 
I understand that is not yet available to be on Git Hub. Could you please send me on email some samples of that part to test on my installation ? My address is gabi_bora2002@yahoo.co.uk
Thanks

**Comment by gabibora** [comment]
@wootwoot1234  I tried to investigate how smartbnb works with airbnb captcha works  and I discovered some things and managed to validate the captcha using this URL `https://www.airbnb.com/airlock?al_id=897928837&key=d306zoyjsyarp7ifhu67rjxn52tv0t20&sid=1:1519893777:ImUyMTU3ZjMwOWNhZTAxMzM1NjYxMTI4NDc3NzczYjU2MmZhY2NlMmNlMTdkNjgxZTQ1OGFmNTM1NTQ2MzZmNzQi--a2706f4d862ad2d9502e9b8b686f82379a166eb6
`  and replacing the al_id and key with the id and key provided by airlock response.  I have managed to get a valid google captcha and validate it but from here  I am stuck, I don't know how validate this.  I guess the airlock system check the IP . On smartbnb after I validated the captcha on airbnb I just hit reconnect on their system and it worked directly, so I guess is some endpoint or parameters related to air lockID or site key

**Comment by wootwoot1234** [comment]
@gabibora thanks again for the help!  I know I keep saying that but I've been working on this issue for over a month and really do appreciate it.

This is what I've figured out so far, given the url you posted:
`https://www.airbnb.com/airlock?al_id=897928837&key=d306zoyjsyarp7ifhu67rjxn52tv0t20&sid=1:1519893777:ImUyMTU3ZjMwOWNhZTAxMzM1NjYxMTI4NDc3NzczYjU2MmZhY2NlMmNlMTdkNjgxZTQ1OGFmNTM1NTQ2MzZmNzQi--`

    al_id=897928837

'al_id' is the airlock id given when you try to login but airbnb needs to verify that it's really you.

    &key=d306zoyjsyarp7ifhu67rjxn52tv0t20

'key' is the api key.  This key is used by browsers accessing the website.  The other key I've seen is `915pw2pnf4h1aiguhph5gc5b2` which is used by the iOS app.  I think each api key has different levels of access to the airbnb api so not everything that works with the browser api key works with the iOS api key and vise versa.

    &sid=1:1519...gxZTQ1OGFmNTM1NTQ2MzZmNzQi--

'sid' is the session id.  You can get a new 'sid' by sending the `x-airbnb-sid` header with an empty string: `"x-airbnb-sid": ""`.  The api will respond with a new sid in the `x-airbnb-sid` header.  It works for me with a POST to `/v2/logins` endpoint and and a GET to the `/v2/airlocks/XXXXXX` endpoint but it probably would work with any api call.

Something I've noticed with smartbnb, is that the link you click to go to the above url first sends you to their server then redirects you to the above url.  I'm not sure why they do that.  It could be that they do some call to the airbnb api before redirecting you or maybe they are just putting together all the url parameters or maybe they want to hide the referrer information.  I'm not sure but something to keep in mind.

**Comment by wootwoot1234** [comment]
@gabibora I forgot to mention that I've gotten to the same place you got to.  When I go to the link you supplied above (with different values of course) after I try to login and I click the 'I'm not a robot' box, it seems to verifies me but the page stays blank.  If you do it though smarbnb it shows you a confirmation after the 'I'm not a robot' box (not a blank page).  So I think smartbnb does some api call before redirecting you to get the url parameters or something, right?

**Comment by gabibora** [comment]
@wootwoot1234  Tom, after  I clicked the 'I'm not a robot' captcha box, I  see a confirmation message with a button named "Done".

also other thing I observed, all the time get this captcha response from airlock I get the same key `6Lf20R0UAAAAAJDj8fQYXmFJWTbSPtvhtjV0VFoy` but is different from `d306zoyjsyarp7ifhu67rjxn52tv0t20` not matter what endpoint I use for login the old one `v1/authorize` or `/v2/logins` 

How important is this SID ? I tried to get an new SID but like you suggested ("x-airbnb-sid": "") and I can't get a SID back

**Comment by gabibora** [comment]
Other thing I observed after a few tests, if I don't validate https://www.airbnb.com/airlock?al_id=940789894&key=6Lf20R0UAAAAAJDj8fQYXmFJWTbSPtvhtjV0VFoy , each time I reload this link the things remain constants for example the  cookies values : `_airbed_session_id` `jitney_client_session_id`  remain the same but for example `jitney_client_session_id`  is different from jitney_client_session_id I receive in Set Cookie header when I get the airlock response with capcha

**Comment by wootwoot1234** [comment]
> Tom, after I clicked the 'I'm not a robot' captcha box, I see a confirmation message with a button named "Done".

Is this different from what you get when you finished the "I'm not a robot" when logging in on smartbnb?  (sorry I forget).

> also other thing I observed, all the time get this captcha response from airlock I get the same key 6Lf20R0UAAAAAJDj8fQYXmFJWTbSPtvhtjV0VFoy but is different from d306zoyjsyarp7ifhu67rjxn52tv0t20 not matter what endpoint I use for login the old one v1/authorize or /v2/logins

the `d306zoyjsyarp7ifhu67rjxn52tv0t20` is the `x-airbnb-api-key` header for (I think) the airbnb website.  In other words, that's how the airbnb api knows it's talking to a browser client and not the iPad app (for example) but that is generally never returned by the api only sent.  What's the `6Lf20R0UAAAAAJDj8fQYXmFJWTbSPtvhtjV0VFoy`?  Is that the `etag` header?  Does the `etag` value have something to do with the "I'm not a robot" captcha?  That might be worth looking into more.  

> How important is this SID ? I tried to get an new SID but like you suggested ("x-airbnb-sid": "") and I can't get a SID back

I don't know how important it is but smartbnb is sending the `sid` as a url parameter to airbnb when directing the user to the "I'm not a robot" page.  I assume they wouldn't put it there unless it was required.

> Other thing I observed after a few tests, if I don't validate https://www.airbnb.com/airlock?al_id=940789894&key=6Lf20R0UAAAAAJDj8fQYXmFJWTbSPtvhtjV0VFoy , each time I reload this link the things remain constants for example the cookies values : _airbed_session_id jitney_client_session_id remain the same but for example jitney_client_session_id is different from jitney_client_session_id I receive in Set Cookie header when I get the airlock response with capcha

That's interesting.  Maybe we need to get the new `jitney_client_session_id` after the captcha is completed and use it to login.

**Comment by wootwoot1234** [comment]
@gabibora I'm using [charles](https://www.charlesproxy.com/) to view the traffic between my iPad and the airbnb api.  When I login using the iPad app the `jitney_client_session_id` never changes.  Not even after it sends me to the "I'm not a robot" page.  It looks like the 'sid' changes or atleast the "I'm not a robot" page returns a different one.

**Comment by gabibora** [comment]
@wootwoot1234  
`Maybe we need to get the new jitney_client_session_id after the captcha is completed and use it to login.` how we can get that ? we can't get cookies from other site ? or we can simulate with JavaScript a GET request to that url to get  jitney_client_session_id  on browser? 

I made yesterday other round of tests also investigated more smartbnb. 

`https://app.smartbnb.io/account/channels/airbnb/captcha/a0e0a087-ee7d-4f05-83b9-af4225eea0a2/before` - this used to redirect to captcha 

https://app.smartbnb.io/account/channels/airbnb/captcha/a0e0a087-ee7d-4f05-83b9-af4225eea0a2/after - this used to re make the login

`a0e0a087-ee7d-4f05-83b9-af4225eea0a2`  is an UUID code and has the same structure and length with `jitney_client_session_id` . I don't know if this is a self generated ID with and UUID generator or is really `jitney_client_session_id`, but I assume that is the real `jitney_client_session_id` 

For the captcha page smartbnb use the same SID for multiple requests for captcha
`sid=1:1520857266:ImUyMTU3ZjMwOWNhZTAxMzM1NjYxMTI4NDc3NzczYjU2MmZhY2NlMmNlMTdkNjgxZTQ1OGFmNTM1NTQ2MzZmNzQi--a2706f4d862ad2d9502e9b8b686f82379a166eb6`

`sid=1:1519893777:ImUyMTU3ZjMwOWNhZTAxMzM1NjYxMTI4NDc3NzczYjU2MmZhY2NlMmNlMTdkNjgxZTQ1OGFmNTM1NTQ2MzZmNzQi--a2706f4d862ad2d9502e9b8b686f82379a166eb6`

The only difference between is `1519893777` that is practically a timestamp, and is the current time stamp I think generated in the moment of login request or it may be the `jitney_client_session_created_at` 

I tried to save `jitney_client_session_id`  and add it to cookies on login along with `x-airbnb-replay-airlock-id` header, still no success but this time I don't get anymore a new `jitney_client_session_id` , only and update timestamp `jitney_client_session_updated_at`. 

I don't know what is missing from airlock request, I suspect that `jitney_client_session_id`  from captcha page must be the same send as cookie when we login.  Is possible to set a cookie in the moment of redirect to captcha page `https://app.smartbnb.io/account/channels/airbnb/captcha/a0e0a087-ee7d-4f05-83b9-af4225eea0a2/before with the initial  `jitney_client_session_id`  ?

**Comment by wootwoot1234** [comment]
There is a lot to take in and to respond to here.  You found some stuff I hadn't noticed, I'm excited to play with this more. Thanks!  :)

> @wootwoot1234
Maybe we need to get the new jitney_client_session_id after the captcha is completed and use it to login. how we can get that ? we can't get cookies from other site ? or we can simulate with JavaScript a GET request to that url to get jitney_client_session_id on browser?

Yes, we can get the `jitney_client_session_id` from a login attempt that returns the captcha response and from what I understand, we can redirect the user to the airbnb captcha url with cookies, like the `jitney_client_session...` cookies.  I'm doing already, look at the `app.get("/verifyCaptcha/:id"` code in the routes.js file I sent you.  I haven't tried to figure out how to get a new `jitney_client_session_id`, I assumed that every time a user tried to login it sent a new one but I haven't verified that and I should!

Note: In the code, I think I might be setting the `jitney_client_session_updated_at` incorrectly, I'll talk more about it below.

>I made yesterday other round of tests also investigated more smartbnb.
>
>https://app.smartbnb.io/account/channels/airbnb/captcha/a0e0a087-ee7d-4f05-83b9-af4225eea0a2/before - this used to redirect to captcha
>
>https://app.smartbnb.io/account/channels/airbnb/captcha/a0e0a087-ee7d-4f05-83b9-af4225eea0a2/after - this used to re make the login
>
>a0e0a087-ee7d-4f05-83b9-af4225eea0a2 is an UUID code and has the same structure and length with jitney_client_session_id . I don't know if this is a self generated ID with an UUID generator or is really jitney_client_session_id, but I assume that is the real jitney_client_session_id

I used [Charles](https://www.charlesproxy.com) to watch my browser's traffic with smartbnb and airbnb. 

from:
https://app.smartbnb.io/account/channels/airbnb/captcha/1ed8388c-2896-41b5-8a7d-c46c46886cbf/before

to:
https://www.airbnb.com/airlock?al_id=1038516952&key=d306zoyjsyarp7ifhu67rjxn52tv0t20&sid=1:1521120552:ImM2N2RiYmJiNTAyNTFmY2U3ODZhODE4YzEzZmU3MDRjNzc2OWI2ODljMjU3ZDJkMSQzNzdiYmM4ZDcyNDg2MWUi--ea83a3c271c3b69a4c16c869f9ead5dff7795344
 
It does not look like the UUID in the url matches the `jitney_client_session_id` that is used.  And after looking into it more, I don't think smartbnb is sending any cookies with thier redirect.  Right now I'm thinking that `jitney_client_session_id` isn't used, it's not sent to airbnb on the redirect.  It maybe used before though.  This is what is sent to airbnb when I'm redrected from smartbnb:

```
:method: GET
:authority: www.airbnb.com
:scheme: https
:path: /airlock?al_id=1038516952&key=d306zoyjsyarp7ifhu67rjxn52tv0t20&sid=1:1521120552:ImM2N2RiYmJiNTAyNTFmY2U3ODZhODE4YzEzZmU3MDRjNzc2OWI2ODljMjU3ZDJkMWQzNzdiYmM4ZDcyNDg2MWUi--ea83a3c271c3b69a4c16c869f9ead5dff7795344
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
referer: https://app.smartbnb.io/account/channels
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
```

>For the captcha page smartbnb use the same SID for multiple requests for captcha
sid=1:1520857266:ImUyMTU3ZjMwOWNhZTAxMzM1NjYxMTI4NDc3NzczYjU2MmZhY2NlMmNlMTdkNjgxZTQ1OGFmNTM1NTQ2MzZmNzQi--a2706f4d862ad2d9502e9b8b686f82379a166eb6
>
>sid=1:1519893777:ImUyMTU3ZjMwOWNhZTAxMzM1NjYxMTI4NDc3NzczYjU2MmZhY2NlMmNlMTdkNjgxZTQ1OGFmNTM1NTQ2MzZmNzQi--a2706f4d862ad2d9502e9b8b686f82379a166eb6
>
>The only difference between is 1519893777 that is practically a timestamp, and is the current time stamp I think generated in the moment of login request or it may be the jitney_client_session_created_at
>
>I tried to save jitney_client_session_id and add it to cookies on login along with x-airbnb-replay-airlock-id header, still no success but this time I don't get anymore a new jitney_client_session_id , only and update timestamp jitney_client_session_updated_at.
>
>I don't know what is missing from airlock request, I suspect that jitney_client_session_id from captcha page must be the same send as cookie when we login. Is possible to set a cookie in the moment of redirect to captcha page https://app.smartbnb.io/account/channels/airbnb/captcha/a0e0a087-ee7d-4f05-83b9-af4225eea0a2/before with the initialjitney_client_session_id` ?

This is really interesting to me and something I hadn't noticed!  Thanks for finding this! 👍 I hadn't noticed that that `1520857266` and `1519893777` in the `sid` was changing!  You're right, it's similar to the `jitney_client_session_updated_at` value but it's not the same. And I think you're right, it is a timestamp.  What I was doing was calculating the current UTC time and using that value to set the `jitney_client_session_updated_at`.  I wasn't doing that for the `sid` because I hadn't noticed it was a timestamp but I think it's the wrong approach anyway.  

Looking into the traffic more, the `sid` and `jitney_client_session_updated_at` are returned as cookies often from airbnb with updated values.  I've been using Charles to watch the traffic between my ipad and airbnb and everytime airbnb returns an updated `sid` or `jitney_client_session_updated_at`value, the ipad uses it with it's next response.  I'm going to play with this more but maybe the reason it hasn't worked yet is because we didn't have the `sid` and `jitney_client_session...' values right?

I'm really hoping that what you found is the issue.  I'll play with the code more and report back.  Thanks!

**Comment by OlegBilous** [comment]
Hi, I also have the question about this.
Would you please specify /verifyAccount api in detail?
I want to know the body parameters of v2/security_checks Airbnb api for phone verification via text, via call, and email verification.
Thanks.

**Comment by programcsharp** [comment]
That's Airbnb's direct API for answering security checks/airlock? -- it looks like you should be able to attempt a login, get an airlock id back, and use `/v2/security_checks` or `/v2/airlocks` to send the verification call/text/email to the user, and then respond with the answer to pass the security check.

Login returns client_error_info.airlock.friction_data and then you can post that friction data to `/v2/airlocks` to request a call/text/email and post the data back again to `/v2/airlocks` when you get it from the user.

That would allow you to do the 2FA entirely in your API without sending folks over to Airbnb.

I tried that method first and never was able to get it working.

So instead I gratuitously stole your method of just sticking in a link to `https://www.airbnb.com/airlock?al_id=@airLockId` and calling it a day. 😝

**Comment by OlegBilous** [comment]
So, verify steps are 2 , one is send verification request, and the other one is send code.
Would you please clarify both apis for Airbnb verification?

**Comment by wootwoot1234** [comment]
@OlegBilous, the login code for my current build on superhosttools.com isn't working 100% of the time and isn't ready to be released, sorry. 

What @programcsharp said is correct (from the little I understand about 2FA with Airbnb).  I'm currently struggling with the captcha (I'm not a robot) page.  Some users authenticate correctly and others don't and I'm not sure why...

**Comment by OlegBilous** [comment]
I saw that for some accounts, superhosttools.com is requiring verification, and it's working.

Would you please let me know your verifyAccount api?
Thanks.

**Comment by wootwoot1234** [comment]
@OlegBilous, I can't share it with you right now.  Sorry.

**Comment by OlegBilous** [comment]
Okay, then.
If it's security, would you please share just api end point for verification?

**Comment by OlegBilous** [comment]
@programcsharp would you explain me how this url work?
https://www.airbnb.com/airlock?al_id=@airLockId
