### ISSUE TITLE
Superhost-Tools won't load on chorme

### ISSUE THREAD

**Issue by Kashk** [wootwoot1234/Superhost-Tools#35]
Hi there,

I'm having an issue loading the site on Chrome. It looks to be working on Safari. 

Just a friendly FYI

Kash

**Comment by wootwoot1234** [comment]
Are you running your own version of the code or are you talking about superhosttool.com?  I do all my testing in chrome and everything is working fine for me.  Maybe try clearing the cache in your browser or just restart your browser.

**Comment by wootwoot1234** [comment]
@Kashk I'm going to close this because it's working great for me in Chrome.  Let me know if you're still having this issue and I'll reopen it.
