### ISSUE TITLE
it sending messages to canceled reservations as well

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#39]
so my rules are working for reservations which have been cancelled, it sending same messages

**Comment by wootwoot1234** [comment]
This might have to do with the number of listings you have.  :)  I'll look into how the code determines if a reservation is canceled and see if there is an issue there.  Can you please let me know next time a reservation is canceled so I can track it and see where the issue is?

**Comment by bkkEvan** [comment]
The reservation was canceled about 1 week ago it supposed to start tomorrow, so it sent all the check in details 9:39 PM, March 12, 2018, Tom <notifications@github.com>:This might have to do with the number of listings you have.  :)  I'll look into how the code determines if a reservation is canceled and see if there is an issue there.  Can you please let me know next time a reservation is canceled so I can track it and see where the issue is?

**Comment by wootwoot1234** [comment]
Can you send me a link to the listing that had the canceled reservation?

**Comment by bkkEvan** [comment]
https://www.airbnb.com/rooms/392529910:00 PM, March 12, 2018, Tom <notifications@github.com>:Can you send me a link to the listing that had the canceled reservation?

**Comment by wootwoot1234** [comment]
I think this bug is fixed.  I'm going to close this issue but let me know if it happens again and I'll reopen it.
