### ISSUE TITLE
superhosttools.com losing account access

### ISSUE THREAD

**Issue by ivanwine** [wootwoot1234/Superhost-Tools#4]
http://superhosttools.com  loses account access, fails to send messages, with no warning, requires account login to airbnb when returning to superhosttools.com

**Comment by wootwoot1234** [comment]
Thanks for letting me know.  I was told about this bug today by someone else too.  

It should have sent you an email letting you know that it failed to connect to Airbnb.  

I just set it up to email the user 3 more time each following day reminding them that their account isn't connecting to airbnb.

Do you mind double checking that you didn't get an email about the account failure?

Thanks!

**Comment by ivanwine** [comment]
I got one email the first time it happened, on the 9th (4:04 pm), but not since then. I tried to login that day, and it consistently failed, but it logged in successfully on the 10th.   Until sometime between then and today.

**Comment by wootwoot1234** [comment]
Ok, I think I've fixed the bug but I'll keep an eye on it.  I just told Superhost Tools to retry every failed account again to make sure they weren't incorrectly flagged.  Thanks for letting me know about the bug and please let me know if you find anything else.
