### ISSUE TITLE
how does the Last Minute Message (second one) in check in rule supposed to work?

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#40]
I thought is for example i have it set 1 day before 8 pm, so if reservation is made after this time it will automatically send? if so it doesnt

**Comment by wootwoot1234** [comment]
Which listing did this fail with?

**Comment by bkkEvan** [comment]
https://www.airbnb.com/rooms/392539310:03 PM, March 12, 2018, Tom <notifications@github.com>:Which listing did this fail with?
