### ISSUE TITLE
the review rule does not leave a review

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#43]
hi
checked - the rule never wrote a review for a guest
i have 2 rules for review. can you check?

**Comment by wootwoot1234** [comment]
Hi @bkkEvan,

Is this a co-host listing because reviews don't work with co-host listings.

**Comment by bkkEvan** [comment]
My original listings as well8:55 PM, March 22, 2018, Tom <notifications@github.com>:Hi @bkkEvan,
Is this a co-host listing because reviews don't work with co-host listings.

**Comment by wootwoot1234** [comment]
That's really weird.  I looked at the error logs and at your account and I don't see any errors but for some reason the review wasn't sent.   The server has also been running with no problems for a while now so that shouldn't be it either.  Have you ever been able to leave a review using superhosttools?

**Comment by bkkEvan** [comment]
No not yet, I set up the rule since I started using superhosttools. Today I decided to check and find out none are sent from the start. I checked Airbnb tells you can leave review during 14 days. Mine is set up on 13 days at 6 pm. Maybe I should set a shorter period of time? 9:33 PM, March 22, 2018, Tom <notifications@github.com>:That's really weird.  I looked at the error logs and at your account and I don't see any errors but for some reason the review wasn't sent.   The server has also been running with no problems for a while now so that shouldn't be it either.  Have you ever been able to leave a review using superhosttools?

**Comment by wootwoot1234** [comment]
Hmmm.  Sounds like it's a bug int he code.  Can you change the time and see if that helps?  I've never waited 13 days to leave a review, I always leave a review after 1 day.

**Comment by bkkEvan** [comment]
I can try to put 12 days? . I don't put 1 day, as lots of guest who comes to me is their first Airbnb experience ever so they compare my place to the hotel, they stay normally 1-2 days and then move to next destination so I want them to have time to compare all review gets nicer9:39 PM, March 22, 2018, Tom <notifications@github.com>:Hmmm.  Sounds like it's a bug int he code.  Can you change the time and see if that helps?  I've never waited 13 days to leave a review, I always leave a review after 1 day.

**Comment by bkkEvan** [comment]
ok there was two reviews in the queue today at 5:30 pm which supposed to send at 6 pm, but they didnt go through

**Comment by bkkEvan** [comment]
@wootwoot1234  ![img_20180323_173532](https://user-images.githubusercontent.com/36990735/37832027-fa03c572-2ed9-11e8-9864-ed4dbbf765b0.jpg)

**Comment by wootwoot1234** [comment]
This must be something related to the large number of listings you have because I know my that reviews are being sent from my account and others.  I'll look into it more and get back to you.

**Comment by bkkEvan** [comment]
@wootwoot1234 thank you

**Comment by wootwoot1234** [comment]
I’ve been watching the logs for a failed review but so far haven’t seen any. When is the your next review?

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38038589-81bdf376-32d5-11e8-97a5-82ab49a614a5.JPG)

**Comment by bkkEvan** [comment]
this was today

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38038680-b934a642-32d5-11e8-95f8-9106582359dc.JPG)

**Comment by bkkEvan** [comment]
this is tomorrow

**Comment by wootwoot1234** [comment]
That's great.  I've added more logging to see what's going on.  Looks like you have a few reviews all being sent at the same time.  Can you spread them out, for example: 7am, 8am, 9am, 10am, 11am...  That way I can see each review in the logs separately and not mixed up.  Also, I'm 12 hours behind Bangkok time and I typically go to sleep by 10pm so if you move them to your morning I can see them today, otherwise I'll have to wait for tomorrow to look at the logs.

**Comment by bkkEvan** [comment]
just did

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38060652-def3f4c4-3315-11e8-945b-d220f373ca5f.JPG)

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38060718-1a794350-3316-11e8-9c2a-0ec9ed7ead89.JPG)

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38060743-32a45366-3316-11e8-8a9b-a2b76299981c.JPG)

you got 5 of them with 1 hour difference

**Comment by wootwoot1234** [comment]
I think there might be more than one bug here.  I'm looking at the logs and I don't see anything for your reviews which should have been sent an hour ago.  Now I'm looking at your messages and it seems like the messages on your dashboard are out of date.  It looks like it's showing you messages from yesterday and you have to click "Next" a couple of times to see the messages for today.  The dashboard seems to have some issue with the timezone or something.  Is that how it's always been?

**Comment by bkkEvan** [comment]
Yes about the dashboard, but I personally care more about reviewing as dashboard I can still figure out and it doesn't affect the guest or my performance Sent from Yandex.Mail for mobile: http://m.ya.ru/ymail7:25 AM, March 29, 2018, Tom <notifications@github.com>:I think there might be more than one bug here.  I'm looking at the logs and I don't see anything for your reviews which should have been sent an hour ago.  Now I'm looking at your messages and it seems like the messages on your dashboard are out of date.  It looks like it's showing you messages from yesterday and you have to click "Next" a couple of times to see the messages for today.  The dashboard seems to have some issue with the timezone or something.  Is that how it's always been?

**Comment by wootwoot1234** [comment]
Ok, can you set another review to go?

**Comment by bkkEvan** [comment]
done

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38087701-4e235746-3383-11e8-826f-0c510bd43d68.JPG)

**Comment by bkkEvan** [comment]
just to let you know i registered other profile at superhosttools as you told me i cant leave reviews like a co-host, so for that profile i set up only reviews for 9 listings
and i got these emails today
![capture](https://user-images.githubusercontent.com/36990735/38087779-a05982d8-3383-11e8-88ef-af2416e218e7.JPG)

**Comment by bkkEvan** [comment]
one of reviews just went through

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38087878-0935c7d0-3384-11e8-8428-ca4f98a7b813.JPG)

**Comment by bkkEvan** [comment]
is a first time it worked for me

**Comment by wootwoot1234** [comment]
Nice!  When is your next review?

**Comment by bkkEvan** [comment]
this one was 7 pm, i got more 8 pm and 9 pm

**Comment by wootwoot1234** [comment]
Sounds good.  Let me know how those go.

**Comment by wootwoot1234** [comment]
You don’t need to create two Superhost Tools accounts, you can add your other Airbnb account to your current Superhost Tools account. In other words, you can have more than one Airbnb account linked to your Superhost Tools account.

**Comment by wootwoot1234** [comment]
How did it go?  Are the reviews working now?  I would like to close out this issue if it's fixed.  :)

**Comment by bkkEvan** [comment]
@wootwoot1234 i got an issue with my second profile 
![capture](https://user-images.githubusercontent.com/36990735/38137325-3c54030a-344e-11e8-81bf-4b972ef2c0e8.JPG)

**Comment by wootwoot1234** [comment]
I know I ask you this every time but I always forget.  Is that account a co-host or the original host for those listings?  Superhost Tools cannot leave reviews for a co-host.  Are those reviews also 12 or 14 days from the checkout date?

**Comment by bkkEvan** [comment]
Original, I is why I created second profile. Yes 12 days11:59 PM, March 30, 2018, Tom <notifications@github.com>:I know I ask you this every time but I always forget.  Is that account a co-host or the original host for those listings?  Superhost Tools cannot leave reviews for a co-host.  Are those reviews also 12 or 14 days from the checkout date?

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38172942-98d1d25a-35df-11e8-85b2-b5c13c897b5f.JPG)

**Comment by bkkEvan** [comment]
@wootwoot1234 Hi, i have problem with reviews for my second profile, for the first profile everything is smooth and nice

**Comment by wootwoot1234** [comment]
Ok, let me look at the logs.  When is your next review with the new account?

**Comment by bkkEvan** [comment]
I think they are all scheduled 6 pm local time, probably your 6 am8:07 AM, April 2, 2018, Tom <notifications@github.com>:Ok, let me look at the logs.  When is your next review with the new account?

**Comment by bkkEvan** [comment]
ok so i got more issues
so when i try to change a rule for listing which is leads to original profile
![capture](https://user-images.githubusercontent.com/36990735/38180767-260d1fa2-3659-11e8-8221-2f943e49a6ee.JPG)
for example this one
it will take me to rules in co-hosting listing instead
![capture](https://user-images.githubusercontent.com/36990735/38180792-4abb8d3e-3659-11e8-9026-a5cd6ae67abd.JPG)
which does not have any rules

**Comment by bkkEvan** [comment]
anyway i went to original listing and change review time to 10 am

**Comment by bkkEvan** [comment]
Rooms named 1-3 Daily and 2-4 Daily

**Comment by wootwoot1234** [comment]
I think I figured out what has been happening.  When an airbnb account was added to superhost tools, old reservations were not added, only current and future reservations.  That's why the reviews haven't been going though.  I've fixed the issue for new accounts added but not for accounts that have already been added like yours.  How long ago did you add this account to superhost tools?

**Comment by bkkEvan** [comment]
First I created a separate account about 3 weeks ago but then re-added to current account couple days ago9:04 PM, April 2, 2018, Tom <notifications@github.com>:I think I figured out what has been happening.  When an airbnb account was added to superhost tools, old reservations were not added, only current and future reservations.  That's why the reviews haven't been going though.  I've fixed the issue for new accounts added but not for accounts that have already been added like yours.  How long ago did you add this account to superhost tools?

**Comment by wootwoot1234** [comment]
Ok, I'm submitting all the fixes now.  It will take about 5 min for everything to update.  Can you schedule a review to go out at 10pm your time?

**Comment by bkkEvan** [comment]
sorry i felled asleepthey are all scheduled now on 8 pm my time (i changed from 6) and 8 am your time    02.04.2018, 21:38, "Tom" <notifications@github.com>:Ok, I'm submitting all the fixes now. It will take about 5 min for everything to update. Can you schedule a review to go out at 10pm your time?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wootwoot1234** [comment]
Great.  Let me know how it goes.

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38253907-0a490f4a-3782-11e8-881c-5fd82428fb50.JPG)

**Comment by bkkEvan** [comment]
@wootwoot1234 same issue as before

**Comment by wootwoot1234** [comment]
Ok, I found and fixed another bug.  Can you schedule a review to go now?

Thanks for taking the time to help me fix this issue.  I've haven't tested a superhost account with two airbnb accounts that have the same listings.  The issue had to do with the listing and account getting confused.  I think it's fixed now though.  Please let me know how it goes.

**Comment by bkkEvan** [comment]
@wootwoot1234  All the future reviews messages for my second profile disappeared from my dashboard, i figured out when tried to schedule some reviews to check how it works

**Comment by wootwoot1234** [comment]
All messages for your second Airbnb account are gone? Are the message rules
still there?

**Comment by bkkEvan** [comment]
yes the review rule is still there in the listing, but no messages for it in the dashboard

**Comment by wootwoot1234** [comment]
How about now, do you see it now?

**Comment by bkkEvan** [comment]
@wootwoot1234 No, not there

**Comment by wootwoot1234** [comment]
Which listing is it so I can take a look?

**Comment by bkkEvan** [comment]
each listing which has SH in the name:

1-1 Daily SH
1-2 Daily SH
1-3 Daily SH 
1-4 Daily SH
2-1 Daily SH 
2-3 Daily SH
2-4 Daily SH 
2-5 Daily SH
2-6 Daily SH

**Comment by wootwoot1234** [comment]
I'm seeing the reviews in your dashboard now.  Did you know you have over 1000 messages scheduled to be sent out, that's not including past massages, that's insane!  :)

I'm still getting a hang of the search and it might need more tweaks but here's a trick you might like.  If you want to find messages for a listing type the listing name with quotes around it.  For example type `"1-2 Daily SH"` and you'll see all the messages/reviews for that listing.

**Comment by wootwoot1234** [comment]
Looks like these reviews failed around 6pm your time:

- Jerry @ Explore Bangkok Perfect Central Spot MRT Lumpini 7
- Vassily @ Perfect Escape Sunny Roof EnSuite

Are those listings co-host?

These reviews were sent successfully around 6pm:

- Robert @ Bangkoker starter package Central MRT Lumphini
- Ariel @ Sathorn MRT Lumphini Little EnSuite

When you get a chance, can you schedule a review to go out with your second account?

**Comment by bkkEvan** [comment]
@wootwoot1234 about first one i could not find any future message at my dashboard for 
each listing which has SH in the name:

1-1 Daily SH
1-2 Daily SH
1-3 Daily SH
1-4 Daily SH
2-1 Daily SH
2-3 Daily SH
2-4 Daily SH
2-5 Daily SH
2-6 Daily SH

like really i used search

**Comment by bkkEvan** [comment]
for 
Jerry @ Explore Bangkok Perfect Central Spot MRT Lumpini 7
Vassily @ Perfect Escape Sunny Roof EnSuite

i am a primary host my first profile

**Comment by bkkEvan** [comment]
I am not sure how to schedule a review with my second account as it does not show any further messages for it

notice that my second account have only 1 review rule for each listings - no other rules

**Comment by wootwoot1234** [comment]
You need to include the quotes in the search.  In other words `"1-1 Daily SH"` not `1-1 Daily SH`

I just made another change to the search so that you can save links to searches.  Clear your browser's cache (or close it and reopen it) and click this link.  

https://superhosttools.com/admin/#!/?s=%221-1%20Daily%20SH%22

Once you find your reviews, let me know when you have them scheduled.

I'm not sure why the other reviews didn't go through.  I'll see if there is an error in the logs.

**Comment by bkkEvan** [comment]
ok i found it thank you, so the problem is all the reviews start 16-18 April and before all are missing even there should be some. Like if the rule start working couple days ago and didnt include any previous reservations

**Comment by wootwoot1234** [comment]
Can you check now?  Are all your reservations showing up?

**Comment by bkkEvan** [comment]
I will be back in one hour, so maybe will answer you in your morning 10:33 AM, April 6, 2018, Tom <notifications@github.com>:Can you check now?  Are all your reservations showing up?

**Comment by wootwoot1234** [comment]
Sounds good.

**Comment by bkkEvan** [comment]
@wootwoot1234 Ok i checked each listing now reviews starting April 13th, ones before are missing

**Comment by bkkEvan** [comment]
ok, lets wait

**Comment by wootwoot1234** [comment]
@bkkEvan do you have any reviews you can schedule to go out now?  I think reviews should be working but I want to make sure.

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38618892-0f8da792-3dc5-11e8-9237-18f8bd095bf4.JPG)
@wootwoot1234  9 pm

**Comment by wootwoot1234** [comment]
You can move it to 8pm and it will send right now.  If you're at your computer, do you mind doing that now?  If not, no big deal, I'll wait till 9.  If you do move it.  Post something here so I know what time to look at the logs.

**Comment by bkkEvan** [comment]
Sorry I got problem with the guest so was busy a bit8:37 PM, April 11, 2018, Tom <notifications@github.com>:You can move it to 8pm and it will send right now.  If you're at your computer, do you mind doing that now?  If not, no big deal, I'll wait till 9.  If you do move it.  Post something here so I know what time to look at the logs.

**Comment by wootwoot1234** [comment]
No problem.  Can you change it to 8pm now?

**Comment by bkkEvan** [comment]
I am not at my description, 9 pm is in 7 min8:43 PM, April 11, 2018, Tom <notifications@github.com>:No problem.  Can you change it to 8pm now?

**Comment by bkkEvan** [comment]
all cool, thank you, tomorrow it will be clear about second profile

**Comment by wootwoot1234** [comment]
@bkkEvan  How'd it go?  Are the reviews working as expected on your second account?

**Comment by bkkEvan** [comment]
All smooth, thank you 7:57 AM, April 14, 2018, Tom <notifications@github.com>:@bkkEvan  How'd it go?  Are the reviews working as expected on your second account?
