### ISSUE TITLE
Rules are not working if guest changed his profile name after reservation 

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#44]
if you need specific reservation details let me know

**Comment by wootwoot1234** [comment]
Hey Evan,

What do you mean not working? They aren’t sending or the name is wrong?

**Comment by wootwoot1234** [comment]
The message is totally gone from the dashboard or has the wrong name?

**Comment by bkkEvan** [comment]
Is totally gone, neither old name nor new one6:25 PM, March 25, 2018, Tom <notifications@github.com>:The message is totally gone from the dashboard or has the wrong name?

**Comment by wootwoot1234** [comment]
Ok, I’ll look into it.

**Comment by wootwoot1234** [comment]
Everything seems ok on my end.  It's hard to debug since she canceled her reservation and messages don't show up after someone has canceled.  Let me know if it happens again.
