### ISSUE TITLE
Rule worked 3 times in a row 

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#45]

**Comment by wootwoot1234** [comment]
The server went down.  It was down for 4 hours.  Did a rule not work for you?

**Comment by bkkEvan** [comment]
I think all worked, probably before it went down some messages got sent 2-3 timesOther than that I am just waiting if you can do Anything for review bug -- Thank you and best regards, Evan +66(0)827960151    26.03.2018, 18:51, "Tom" <notifications@github.com>:The server went down. It was down for 4 hours. Did a rule not work for you?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wootwoot1234** [comment]
A message got sent more than once?  Can you tell me which message and to which guest?

**Comment by wootwoot1234** [comment]
Does superhost tools show 3 messages in the dashboard?  Or did you get the email for that message 3 times?  It's possible that this is a bug with airbnb.  Sometimes they will show a message as sent more than once.

**Comment by bkkEvan** [comment]
On superhost dashboard is only one
i personally dont think is an issue as guests will not get upset with that

**Comment by wootwoot1234** [comment]
This has happened to me as well.  If it's not showing as multiple messages on Superhost Tools then it only sent it one.  Every message that is sent is immediately added to the history.   I think it's a bug with Airbnb.
