### ISSUE TITLE
Check up rule started ignoring 2 nights minimum stay and showing messages for 1 night reservations

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#46]

**Comment by wootwoot1234** [comment]
That’s weird, I haven’t changed anything with that code in a while. Can you tell me which reservation and which message so I can take a look?

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38024448-3d96fccc-32af-11e8-93fa-6826bf10e45b.JPG)

**Comment by bkkEvan** [comment]
i did cancel them before they were sent

**Comment by wootwoot1234** [comment]
Thanks for finding this bug.  It's now fixed.  The messages that you disabled will still show but any other rules with min nights will work now.    Can you verify that it's fixed?

**Comment by bkkEvan** [comment]
Sure verified,  if you can only fix one with reviews as well it will be the smoothest experience ever8:34 PM, March 28, 2018, Tom <notifications@github.com>:Thanks for finding this bug.  It's now fixed.  The messages that you disabled will still show but any other rules with min nights will work now.    Can you verify that it's fixed?
