### ISSUE TITLE
Cant disable future message rule

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#49]
I want to disable all future reviews for the Guest named Somchai
I put Somchai in the search - scheduled reviews appear on dashboard
i select the drop down in the top right corner press actions and select Disable
nothing happens message does not get disabled

**Comment by wootwoot1234** [comment]
I'll look into it right now.  Thanks for creating a new issue.  :)

**Comment by wootwoot1234** [comment]
Ok, I fixed it.  Let me know if it works for you.

**Comment by bkkEvan** [comment]
work with most messages but not with this two
![capture](https://user-images.githubusercontent.com/36990735/38231572-52e99138-373d-11e8-98d9-b03e8189139f.JPG)

**Comment by bkkEvan** [comment]
and these two 
![capture](https://user-images.githubusercontent.com/36990735/38231640-a43bc290-373d-11e8-85c4-84b2578c3134.JPG)

**Comment by wootwoot1234** [comment]
I figured out the issue and am working on a fix now.  There are duplicate messages (just in the dashboard, it's different code then the code that sends the messages, it won't send the messages more than once).  I'm working on figuring out why it's happening, it has to do with the new dashboard layout.  I'll let you know when I have a fix.

**Comment by wootwoot1234** [comment]
Ok, I think it's fixed.  Can you verify that it's working now and then I'll look into https://github.com/wootwoot1234/Superhost-Tools/issues/43 again.

**Comment by bkkEvan** [comment]
yes thats fixed
