### ISSUE TITLE
Booking confirmation rule didnt work yesterday 11 pm (your today 11 am)

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#50]
![capture](https://user-images.githubusercontent.com/36990735/38280061-76fd7ef0-37cd-11e8-95da-30de67db0c92.JPG)

**Comment by wootwoot1234** [comment]
Which account is this for? Are other messages going out? If other messages
are working fine, are other booking confirmation messages going out?

**Comment by bkkEvan** [comment]
the booking confirmation rule is in my main profile which is co-hosting for this listing, i didnt get any new reservations since then so hard to tell if it was a temporary thing

**Comment by wootwoot1234** [comment]
I guess it could have happened when I was restarting the server but let me
know if it works next time you get a booking.  I'll keep it open to make
sure it's working.

**Comment by wootwoot1234** [comment]
Have you gotten any new booking?  Let me know if this is still an issue, thanks!

**Comment by bkkEvan** [comment]
you can close this one

**Comment by bkkEvan** [comment]
@wootwoot1234 Happened again today

**Comment by bkkEvan** [comment]
![screenshot_2018-04-07-09-49-18](https://user-images.githubusercontent.com/36990735/38452131-178a3d1c-3a68-11e8-9c80-0afc0ed630e1.png)

**Comment by bkkEvan** [comment]
today around 9:09 am, i waited about 40 min then replied myself

**Comment by bkkEvan** [comment]
listing StudioBKK Lumphini Home Stay Sathorn MRT Lumphini

**Comment by wootwoot1234** [comment]
Ok, thanks for pointing this out. I’m now aware of the issue and I think I know how to fix it but it will take a day or two to fix. I would recommend keeping an eye on booking confirmations till it’s fixed.
