### ISSUE TITLE
booking confirmation rule triggers again after reservation alteration

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#52]
so the guest altered reservation for the same dates but different listing and they got booking confirmation message again right away

**Comment by wootwoot1234** [comment]
I don't think I've ever seen that.  Did they cancel and rebook or alter their reservation to another listing?  I didn't know you could change listings.  What's the guest's name?

**Comment by bkkEvan** [comment]
no she used alteration tool. that was reservation with Zaynub for May 2 -8

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38448619-b6b73554-3a2f-11e8-9a3e-6eef6c1d08e5.JPG)

**Comment by wootwoot1234** [comment]
Wow, I didn't know you could change a guest's listing.  That's great to know!  I fixed the issue, it shouldn't happen again.  I'll close this for now but let me know if it happens again.
