### ISSUE TITLE
Search at dashboard stopped working

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#53]
for example i want to search for guests name 录宣怡 and search would not
i cant read or speak Chinese i just copy-paste from airbnb

**Comment by bkkEvan** [comment]
actually its something wrong with search i tried to search for Maria and it didnt work either

**Comment by bkkEvan** [comment]
neither when i put "Generous space and great views over Silom&Sathorn!"

**Comment by wootwoot1234** [comment]
It's fixed, clear the cache on your browser and try again.

**Comment by bkkEvan** [comment]
Booking confirmation rule does not work, I sent you a message in closed thread 1:52 AM, April 8, 2018, Tom <notifications@github.com>:It's fixed, clear the cache on your browser and try again.

**Comment by wootwoot1234** [comment]
Ok, I’ll reopen that issue, is this bug fixed?
