### ISSUE TITLE
Rules working are on the wrong date

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#54]
![capture](https://user-images.githubusercontent.com/36990735/38461798-c5b8a158-3b03-11e8-9b27-3568a1f58157.JPG)
this should be yesterday

**Comment by bkkEvan** [comment]
actually all messages from yesterday are showing to be sent today

**Comment by wootwoot1234** [comment]
The server went down for about 6 hours, could that be the issue? Are all
messages showing as sent 1 day different?

**Comment by bkkEvan** [comment]
all starting yesterday 10 am until today 10 am didnt send

**Comment by wootwoot1234** [comment]
Wait, all your messages for the last 24 hours didn’t send?!?

**Comment by bkkEvan** [comment]
exactly

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38462640-d0fc50c6-3b14-11e8-8558-df2a7f21a04e.JPG)

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38462645-e3d19c2e-3b14-11e8-8ce0-2b5b07029437.JPG)

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38462650-f76c4d92-3b14-11e8-93c1-8a42c42a0f41.JPG)

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38462660-0cc74e76-3b15-11e8-9e9f-c11e926d639d.JPG)

**Comment by bkkEvan** [comment]
i disabled all which doesnt make sence to send now, but the rest when you fix it can you put to send through?

**Comment by bkkEvan** [comment]
also i got today an email report about sent messages - if it makes server work any harder (have no idea how it works with servers) you can disable that feature as it is not necessary

**Comment by wootwoot1234** [comment]
The reason the messages aren’t going out is related to the same issue your
have with booking confirmation messages. The Superhost Tools server is
connecting Airbnb’s server too often and Airbnb has started to block some
connections. I just slowed it down to check for new bookings every 20 min
instead of ever 5 min. Hopefully that fixes it for now and I’ll look into
it more tomorrow.

**Comment by bkkEvan** [comment]
Let's see, I am wondering how other guys doing that10:38 AM, April 8, 2018, Tom <notifications@github.com>:The reason the messages aren’t going out is related to the same issue your
have with booking confirmation messages. The Superhost Tools server is
connecting Airbnb’s server too often and Airbnb has started to block some
connections. I just slowed it down to check for new bookings every 20 min
instead of ever 5 min. Hopefully that fixes it for now and I’ll look into
it more tomorrow.

**Comment by wootwoot1234** [comment]
Multiple servers maybe?

**Comment by bkkEvan** [comment]
Not our cup of tea,right?10:42 AM, April 8, 2018, Tom <notifications@github.com>:Multiple servers maybe?

**Comment by wootwoot1234** [comment]
Each server costs money... there might be some ways to make the code more
efficient. I’ll keep working on it.

**Comment by bkkEvan** [comment]
Could you host some of the code on other websites? I have two which are not very popular 10:45 AM, April 8, 2018, Tom <notifications@github.com>:Each server costs money... there might be some ways to make the code more
efficient. I’ll keep working on it.

**Comment by wootwoot1234** [comment]
Thanks but it’s not that easy. I’ll see what I can figure out. Let me know
if it starts working again.

**Comment by roblafave** [comment]
@wootwoot1234 - First of all, thank you for sharing this messaging tool with the community. Second, I wanted to report that I'm experiencing the same issue of unsent messages. I think the issue has only surfaced over the past day or so.

**Comment by bkkEvan** [comment]
So it randomly sent couple non-relevant to timing messages around midnight-2 am and then went down again

**Comment by wootwoot1234** [comment]
I'm hoping I found the issue.  Can you check your messages starting now and see if they are working correctly?

**Comment by bkkEvan** [comment]
Thank you, everything seem working
