### ISSUE TITLE
10am-12pm no rules are working

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#55]
it was working fine until this morning an now again not

**Comment by bkkEvan** [comment]
lets change it

**Comment by bkkEvan** [comment]
now?

**Comment by wootwoot1234** [comment]
Yeah, you need to clear the cache on your browser.  I just submitted some
changes to the add account code.  Close your browser completely and reopen
it.  I just made a backup so go ahead and change your password on airbnb

**Comment by bkkEvan** [comment]
done

**Comment by bkkEvan** [comment]
when it will work again?

**Comment by wootwoot1234** [comment]
Are you asking when will the next message will send?  When it's scheduled to send I hope.  :)

**Comment by bkkEvan** [comment]
I got 3 reservations after I changed the password 8:43 PM, April 10, 2018, Tom <notifications@github.com>:Are you asking when will the next message will send?  When it's scheduled to send I hope.  :)

**Comment by bkkEvan** [comment]
It supposed to send booking confirmation rule and two check in rules8:43 PM, April 10, 2018, Tom <notifications@github.com>:Are you asking when will the next message will send?  When it's scheduled to send I hope.  :)

**Comment by wootwoot1234** [comment]
I'm not seeing the errors on your account.  Do you see them in the dashboard?  I need to know the listing, guest and the time (your time) it was supposed to send.

**Comment by bkkEvan** [comment]
2/36 daily JohnBooked 37 min agoShould receive confirmation and check in immediately 8:56 PM, April 10, 2018, Tom <notifications@github.com>:I'm not seeing the errors on your account.  Do you see them in the dashboard?  I need to know the listing, guest and the time (your time) it was supposed to send.

**Comment by wootwoot1234** [comment]
I'm about to head out for a bit but will look at this in an hour.

Were there other messages that failed just now?  Did any work?  I'm trying to figure out if there is a pattern to help me find the issue.  Were they all booking confirmation messages or last minute booking messages?

**Comment by wootwoot1234** [comment]
I've re-written the booking message code but haven't enabled it yet.  The server is still running the old code because I want to run a few tests on it before it goes live.  I didn't want it to start sending the wrong message.  Let me know next time you get a booking and which messages (just the title of the message rule) it should have sent

**Comment by bkkEvan** [comment]
Room7-seven: Explore Bangkok perfect Central spotBooked 1 hour ago around 2am by guest CharlieShould sent:Booking confirmation 11:25 PM, April 10, 2018, Tom <notifications@github.com>:I've re-written the booking message code but haven't enabled it yet.  The server is still running the old code because I want to run a few tests on it before it goes live.  I didn't want it to start sending the wrong message.  Let me know next time you get a booking and which messages (just the title of the message rule) it should have sent

**Comment by bkkEvan** [comment]
thank you, all seem working except reviews

**Comment by wootwoot1234** [comment]
All reviews or just your second account? We’re still waiting till the 13th
to test the second account, right? When did the last review fail?

**Comment by bkkEvan** [comment]
![capture](https://user-images.githubusercontent.com/36990735/38616397-24b45f5a-3dbe-11e8-9239-a424b32ce830.JPG)
my main account failed today at 6 pm

**Comment by wootwoot1234** [comment]
Ok, thanks.    Superhost tools normally emails multiple times when it can't leave a review but it looks like it only emailed once which is weird.  Can you check your airbnb account and see if the review was actually left?

**Comment by wootwoot1234** [comment]
I looked at the logs and that review failed because you already left that guest a review!  The message should be clearer, sorry about that.

I'm going to close this issue.  Let's keep talking about the review issues here https://github.com/wootwoot1234/Superhost-Tools/issues/43
