### ISSUE TITLE
Unable to link Airbnb account

### ISSUE THREAD

**Issue by sylvainairbnb** [wootwoot1234/Superhost-Tools#56]
Hello there. 
I've tried to link my Airbnb account multiple times but it fails every time. 
When trying to link the account, it asks me to verify that I'm not a robot, I do as explained, but when I come back to the superhosttool website, and when I click to the next button, it asks me to verify again even though I've already done it. And now it tells that I've tried too many times and doesn't even let me try. Can you please help me fix this?

**Comment by wootwoot1234** [comment]
Have you tried completing the verification (I’m not a robot) a few times?
Sometimes it can ask you to complete the I’m not a robot page a few times,
I’ve seen it ask up to 5 times in a row.

Let me know if that works.

Tom

**Comment by sylvainairbnb** [comment]
Hello. Thanks for the quick answer! 
Yes I've tried at least 15 times. Maybe much more I didn't count. I tried until the webpage told me I couldn't try again, since I've tried too many times, there is a message saying that Airbnb needed me to wait later. I will try again but I'm sure I did everything right. Maybe it's because I tried with iOS device ( I tried both with my ipad and iphone, I don't have a PC at the moment ) ?

**Comment by sylvainairbnb** [comment]
I tried again and it finally worked :-) 
It didn't even need me to do the I'm not a robot verification once this time. 
Really don't know why it wasn't working yesterday and why it was keep asking me to do the verification. 
Thanks anyway, and thanks for the application, it sounds very useful. 
Cheers.

**Comment by wootwoot1234** [comment]
happy to hear it.  Let me know if you have other any issues.
