### ISSUE TITLE
Not working last 9 hours

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#57]
let me know if you need infos like that, now everything works

**Comment by wootwoot1234** [comment]
I’ve been traveling and haven’t had time to look into this. I hope to find
some time in the next few days. Are messages still failing?

**Comment by bkkEvan** [comment]
It's all good now. Have a wonderful trip 11:49 PM, April 22, 2018, Tom <notifications@github.com>:I’ve been traveling and haven’t had time to look into this. I hope to find
some time in the next few days. Are messages still failing?

**Comment by bkkEvan** [comment]
@wootwoot1234 booking confirmation rule was not working last 9 hours. can you check?

**Comment by bkkEvan** [comment]
its back at 7 am

**Comment by bkkEvan** [comment]
dont bother
