### ISSUE TITLE
Accessing reservation financials

### ISSUE THREAD

**Issue by programcsharp** [wootwoot1234/Superhost-Tools#59]
Hey, it's me again. The batch update stuff has been working a treat!

Now I'm getting further into the details and trying to access all of the financial details for a reservation so I can generate financial reports. @wootwoot1234 wondering if you've run into this or have any ideas -- if not, hoping this is useful info for you as well.

Some info is available at https://api.airbnb.com/v2/reservations?role=host&host_id=12345 (no format param passed) or https://api.airbnb.com/v2/reservations/1234567890...

```        {
            "airbnb_credit_amount_native": 0,
            "airbnb_credit_breakdown": [],
            "cancellation_policy": "super_strict_60_grace_period",
            "cancellation_policy_formatted": "Super Strict 60 Days",
            "coupon_price_native": 0,
            "extras_price": 0,
            "extras_price_formatted": "$0",
            "extras_price_native": 0,
            "guest_fee": 143,
            "guest_fee_formatted": "$143",
            "guest_fee_native": 143,
            // id's redacted
            "per_night_price_formatted": "$399",
            "per_night_price_native": 399,
            "security_price_formatted": "$300",
            "security_price_native": 300,
            "subtotal_native": 1197
        }
```

But that's only guest facing info, no host fees, resolution adjustments, or payout info.

https://api.airbnb.com/v2/payouts gives a list of empty payouts -- I can't find a format that will make detail expand.

https://api.airbnb.com/api/v2/payout_transactions?user_id=12345  (id's redacted) gives some very detailed info on the payout, but no fee info (host fee, cleaning etc). It includes resolution payouts but I don't see a way to match that up to the relevant reservation.

```
        {
            "currency_amount": {
                "amount_micros": 779000000,
                "amount_formatted": "$779.00",
                "currency": "USD",
                "is_micros_accuracy": true
            },
            "days_to_process": 3,
            "estimated_deposit_timestamp": "2018-05-23T17:40:41+00:00",
            "filtered_currency_amounts": null,
            "localized_transaction_code_for_display": null,
            "payout_timestamp": "2018-05-18T17:40:41Z",
            "product_transactions": [
                {
                    "allocation_split_items": [],
                    "currency_amount": {
                        "amount_micros": 779000000,
                        "amount_formatted": "$779.00",
                        "currency": "USD",
                        "is_micros_accuracy": true
                    },
                    "days_to_process": null,
                    "end_timestamp": "2018-06-15T15:00:00Z",
                    "estimated_deposit_timestamp": "2018-04-18T19:00:00+00:00",
                    "guest_names": [
                        "Foo Bar"
                    ],
                    "has_payout_schedule": false,
                    "is_allocation_line_item": false,
                    "is_capital_product_repayment": false,
                    "is_early_host_payout": false,
                    "is_filtered_out": null,
                    "is_tax_withholding": false,
                    "product_type": "Reservation2",
                    "ready_for_release_at": "2018-04-14T19:00:00Z",
                    "release_time_offset": 68400,
                    "start_timestamp": "2018-06-13T19:00:00Z",
                    "transaction_type": "Reservation"
                }
            ],
            "related_payout_transaction_tokens": [],
            "release_time_offset": 63641,
        },
```

https://api.airbnb.com/v2/resolutions gives apparently a list of resolutions, but I can't figure out how to get it to expand out the detail.

So there's a ton of info there, almost enough to go end to end. Things I can't find:
 - Host fee
 - Cleaning/linen/management/service fees
 - Linkage between reservations and resolutions

Any idea where I might find the additional info?

**Comment by programcsharp** [comment]
I found part of the answer!

You can get the fee breakdown by calling /reservations with _format=for_mobile_host. That gets a ton of info and gives you host fee, cleaning fee, etc... but strangly enough not guest fee.

For guest fee, you have to call /reservations with no _format param.

Still looking for a way to link reservations to resolutions.

**Comment by wootwoot1234** [comment]
This is outside of the scope of superhost tools and I haven't looked into getting the financials from airbnb.com.  Sorry, I wish I could be of more help.

**Comment by programcsharp** [comment]
No problem, just figured you might want to pull in that data to circle up and analyze the results of the pricing tool. If not, I won't clutter up your repo with more issues.

I wish there was a central mailing list or something to share knowledge for those of us unofficially working with the API -- what different operations are available etc. Or stuff like the method to get around flagged accounts you mentioned in #60 -- will you be releasing that code here at some point or are you taking this all private from now on?
