### ISSUE TITLE
Its error starting 10 am

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#62]
Hi Tom, Hope you are doing fine

**Comment by wootwoot1234** [comment]
Thanks.  I'm working on it now...

**Comment by bkkEvan** [comment]
also it just sent booking confirmation rule to many guests without no-reason

**Comment by bkkEvan** [comment]
like i am on page 5 now and it sent to all my future guests

**Comment by wootwoot1234** [comment]
I'm sorry!  I don't know why it did that.  The server went down and I had to completely rebuild it.  For some reason it sent out booking confirmation messages.  I'm really sorry, I wish there was something I could do.  :(
