### ISSUE TITLE
Logging out from Airbnb account every 2 days

### ISSUE THREAD

**Issue by AnaMarty** [wootwoot1234/Superhost-Tools#66]
SuperHost tools has problems with logging into Airbnb account every 2 days. 
It happened at Jul, 1, Jul, 2, Jul, 14, Jul, 15 and Jul, 17.

**Comment by wootwoot1234** [comment]
Hi @AnaMarty,

I'm sorry this is happening to you.  I'm not sure why.  I'll keep looking into it, Are you still having the problem or has it mellowed out?
