### ISSUE TITLE
it stopped sending messages to some of my co-hosting listings 

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#67]
for example guest 相越 didnt get any yesterday

and when i sent this message after 8 minutes it sent guest the last minute booking confirmation

**Comment by bkkEvan** [comment]
my guest Leo made 7 reservations yesterday for different listings, rules worked for him only 3 times

**Comment by wootwoot1234** [comment]
I think this issue has been resolved as of 10 hours ago.  Let me know if it happens again and Ill re-open it.
