### ISSUE TITLE
it did send booking confirmation randomly again 

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#70]
check my guest Sabino, 
Klaus 
Pallavi
Korey
Bocci
Mauricio
Chrisje

**Comment by wootwoot1234** [comment]
I just added some new code to make sure it didn't miss any reservations.  A sort of backup.  Can you do me a favor and double check on airbnb.com if it sent it twice or did it send it for the first time?

**Comment by bkkEvan** [comment]
there was couple of "crazy" days August 2, July 26, July 18

**Comment by wootwoot1234** [comment]
I'm trying to understand why this is happening.  Did you change the rule?  Did you move the rule from being just for this listing to a rule for all listings?  Can you think of anything else you might have changed?  Thanks for the help.

**Comment by bkkEvan** [comment]
i definitely didnt change anything in the rule since 3-4 months

**Comment by bkkEvan** [comment]
i might did change things in the listing - i do all the time, but not on superhost

**Comment by wootwoot1234** [comment]
Ok.  Let me keep looking at the code...

**Comment by bkkEvan** [comment]
i actually cant use All listings rules as they will work two times for main host and co-host

**Comment by wootwoot1234** [comment]
Oh that's right!  I forgot you were doing that.  Do you have two accounts connected because of reviews?

**Comment by bkkEvan** [comment]
Yes because of reviews 8:36 PM, August 2, 2018, Tom <notifications@github.com>:Oh that's right!  I forgot you were doing that.  Do you have two accounts connected because of reviews?

**Comment by wootwoot1234** [comment]
I think this is fixed now.  Let me know if it happens again and I'll reopen this issue.
