### ISSUE TITLE
New guest received booking confirmation message but didnt receive the last minute directions

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#71]
that was my guest John

**Comment by wootwoot1234** [comment]
Ok.  This actually happened to me too.  

What date and time (your timezone) was the booking made?  What date and time is the normal check in for that unit?

**Comment by bkkEvan** [comment]
it came in 11:49 am today August 3 

reservation was made for tonight so normally guest should receive last minute directions additional to welcoming message

**Comment by wootwoot1234** [comment]
So the booking was at 11:49am on the same day as the check in?

How often do you get bookings like this that get the last minute message?  The reason I ask is because I'm going to need more last minute booking to test the bug with.

**Comment by bkkEvan** [comment]
i get the same day reservations couple times a week

**Comment by bkkEvan** [comment]
i will let you know

**Comment by bkkEvan** [comment]
Just happened with my other guests who booked for tonight:

Thorwald
Nakura

**Comment by wootwoot1234** [comment]
Ok, thanks.  Keep telling me when it happens.

**Comment by bkkEvan** [comment]
Leo
Dima 
Mi 
Ryoma

**Comment by wootwoot1234** [comment]
Sorry I just saw this.  You got 4 new last minute bookings?

**Comment by bkkEvan** [comment]
Yes, correct 1:24 AM, August 4, 2018, Tom <notifications@github.com>:Sorry I just saw this.  You got 4 new last minute bookings?

**Comment by wootwoot1234** [comment]
Wow, crazy.  I submitted a fix to the code just a few minutes ago.  Let me know if your next last minute booking goes out.
