### ISSUE TITLE
Enhancement for listings tap

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#73]
Enhancement

at the listings tab make it possible to return/update listings names from your profile without loosing data on messages

ability to see which listings are listed and which are unlisted

**Comment by wootwoot1234** [comment]
Can you explain in more detail what you mean by:

>make it possible to return/update listings names from your profile without loosing data on messages

**Comment by bkkEvan** [comment]
I did edit listing title names in my Superhostools profile the way they stopped matching my airbnb listing names (i thought i would remember which is which) but now i have a hard time to identify -- Thank you and best regards, Evan +66(0)827960151    26.08.2018, 03:03, "Tom" <notifications@github.com>:Can you explain in more detail what you mean by:make it possible to return/update listings names from your profile without loosing data on messages—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wootwoot1234** [comment]
You should be able to go to the listing's settings page and delete the nickname and that should put the original listing name back.  Is that what you wanted?

**Comment by wootwoot1234** [comment]
I also added the listing title to the listing setting dialog so you know which listing it is when editing the listing nickname.  I'm going to close this unless you think it's still unclear?
